name:                fib-cli
version:             1.1.2.3
github:              "booniepepper/fib"
license:             BSD3
author:              "J.R. Hill"
maintainer:          "justin@so.dang.cool"
copyright:           "Copyright (c) 2021 J.R. Hill"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing the package
synopsis:            A CLI for calculating Fibonacci numbers.
category:            Command Line

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/boonipepper/fib#readme>

dependencies:
- base >= 4.7 && < 5
- fibonacci == 0.2.0.1
- gutenberg-fibonaccis == 1.1.0

library:
  source-dirs: src

executables:
  fib:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fib-cli
    - fibonacci
    - gutenberg-fibonaccis

tests:
  fib-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fib-cli
    - hspec
    - process
