on:
  release:
    types: [created]
name: Add artifacts to release
jobs:
  add-artifacts:
    name: stack build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '8.8.4' # Exact version of ghc to use
          # cabal-version: 'latest'. Omitted, but defaults to 'latest'
          enable-stack: true
          stack-version: 'latest'
      - run: |
          stack build
          cd .stack-work/install/*/*/*/bin/
          tar -czvf fib-x86_64-linux.tgz fib
      - uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '.stack-work/install/*/*/*/bin/*.tgz'

